In [21]:
import pandas as pd
import os

In [22]:
# Load the datasets

d1_original = pd.read_csv("datasets/dreaddit-train.csv")
d2_original = pd.read_csv("datasets/reddit_train.csv")
d3_original = pd.read_csv("datasets/train.csv")

In [23]:
# Create a copy of the datasets

d1_original.to_csv("copy/d1.csv", index=False)
d2_original.to_csv("copy/d2.csv", index=False)
d3_original.to_csv("copy/d3.csv", index=False)

In [ ]:
# FOR DATASET D1

In [24]:
d1 = pd.read_csv("copy/d1.csv")
d1.head(3)

,post,question,response
0,"Post: He said he had not felt that way before,...","Question: The answer to the question ""Does th...",yes. Reasoning: The poster's language and beha...
1,"Post: Hey there r/assistance, Not sure if this...","Question: The answer to the question ""Does th...",no. Reasoning: The language used in the post ...
2,Post: My mom then hit me with the newspaper an...,"Question: The answer to the question ""Does th...",yes. Reasoning: The poster's language reflects...

In [32]:
# CLEAN THE DATASET D1

In [26]:
# Remove Duplicates
d1.drop_duplicates(inplace=True)

# Remove Post word:
d1["post"] = d1["post"].str.replace(r"(?i)^post:\s*", "", regex=True)

# Remove Question word:
d1["question"] = d1["question"].str.replace(r"(?i)Question:\s*", "", regex=True)

# Extract Yes/No
d1["stress_label"] = d1["response"].str.extract(r"(?i)^(yes|no)")

# Extract Reasoning Part
d1["stress_label"] = d1["response"].str.extract(r"(?i)^(yes|no)")


# Extract Reasoning Part
d1["reasoning"] = d1["response"].str.split("Reasoning:", expand=True)[1]
# Clean reasoning column
d1["reasoning"] = d1["reasoning"].str.strip()


# Lowercase Everything
d1["post"] = d1["post"].str.lower()
d1["question"] = d1["question"].str.lower()
d1["reasoning"] = d1["reasoning"].str.lower()
d1["stress_label"] = d1["stress_label"].str.lower()


# Remove NaN values 
d1 = d1.dropna()

# Drop Old Response Column
d1.drop(columns=["response"], inplace=True)


d1.head(3)

,post,question,stress_label,reasoning
0,"he said he had not felt that way before, sugge...","the answer to the question ""does the poster s...",yes,the poster's language and behavior indicate th...
2,my mom then hit me with the newspaper and it s...,"the answer to the question ""does the poster s...",yes,the poster's language reflects a high level of...
3,"until i met my new boyfriend, he is amazing, h...","the answer to the question ""does the poster s...",yes,the poster's language reflects a high level of...

In [27]:
# Label Encode Yes/No

d1["stress_label"] = d1["stress_label"].map({"yes": 1, "no": 0})
d1["stress_label"].value_counts()

d1.head(3)

,post,question,stress_label,reasoning
0,"he said he had not felt that way before, sugge...","the answer to the question ""does the poster s...",1,the poster's language and behavior indicate th...
2,my mom then hit me with the newspaper and it s...,"the answer to the question ""does the poster s...",1,the poster's language reflects a high level of...
3,"until i met my new boyfriend, he is amazing, h...","the answer to the question ""does the poster s...",1,the poster's language reflects a high level of...

In [29]:
# Safe back the file into the d1

d1.to_csv("copy/d1.csv", index=False)

In [ ]:
# FOR DATASET D2

In [31]:
d2 = pd.read_csv("copy/d2.csv")
d2.head(3)

,post,question,response
0,Post: How to avoid a relapse? I've been having...,"Question: The answer to the question ""Does th...",yes. Reasoning: The post displays a significan...
1,Post: This is how I feel and I have a slight s...,"Question: The answer to the question ""Does th...",yes. Reasoning: The post exhibits a clear and ...
2,Post: Advice for getting back in touch with ev...,"Question: The answer to the question ""Does th...",yes. Reasoning: The post conveys a sense of di...

In [33]:
# CLEAN THE DATASET D2

In [34]:
# Remove Duplicates
d2.drop_duplicates(inplace=True)

# Remove Post word:
d2["post"] = d2["post"].str.replace(r"(?i)^post:\s*", "", regex=True)

# Remove Question word:
d2["question"] = d2["question"].str.replace(r"(?i)Question:\s*", "", regex=True)

# Extract Yes/No
d2["stress_label"] = d2["response"].str.extract(r"(?i)^(yes|no)")

# Extract Reasoning Part
d2["stress_label"] = d2["response"].str.extract(r"(?i)^(yes|no)")


# Extract Reasoning Part
d2["reasoning"] = d2["response"].str.split("Reasoning:", expand=True)[1]
# Clean reasoning column
d2["reasoning"] = d2["reasoning"].str.strip()


# Lowercase Everything
d2["post"] = d2["post"].str.lower()
d2["question"] = d2["question"].str.lower()
d2["reasoning"] = d2["reasoning"].str.lower()
d2["stress_label"] = d2["stress_label"].str.lower()


# Remove NaN values 
d2 = d2.dropna()

# Drop Old Response Column
d2.drop(columns=["response"], inplace=True)


d2.head(3)

,post,question,stress_label,reasoning
0,how to avoid a relapse? i've been having a par...,"the answer to the question ""does the poster s...",yes,the post displays a significant amount of emot...
1,this is how i feel and i have a slight sense i...,"the answer to the question ""does the poster s...",yes,the post exhibits a clear and profound sense o...
2,advice for getting back in touch with everyday...,"the answer to the question ""does the poster s...",yes,the post conveys a sense of disengagement and ...

In [35]:
# Label Encode Yes/No

d2["stress_label"] = d2["stress_label"].map({"yes": 1, "no": 0})
d2["stress_label"].value_counts()

d2.head(3)

,post,question,stress_label,reasoning
0,how to avoid a relapse? i've been having a par...,"the answer to the question ""does the poster s...",1,the post displays a significant amount of emot...
1,this is how i feel and i have a slight sense i...,"the answer to the question ""does the poster s...",1,the post exhibits a clear and profound sense o...
2,advice for getting back in touch with everyday...,"the answer to the question ""does the poster s...",1,the post conveys a sense of disengagement and ...

In [36]:
# Safe back the file into the d2

d2.to_csv("copy/d2.csv", index=False)

In [ ]:
# FOR DATASET D3

In [38]:
d3 = pd.read_csv("copy/d3.csv")
d3.head(3)

,post,question,response
0,Post: All my life i've been going through shit...,"Question: The answer to the question: ""Does t...",yes. Reasoning: 1. The individual mentions goi...
1,Post: All my life i've been going through shit...,"Question: The answer to the question: ""Does t...",yes. Reasoning: \n\n1. The post mentions goin...
2,Post: Give me one good reason I should not kil...,"Question: The answer to the question: ""Does t...",yes. Reasoning: 1. The individual expresses f...

In [40]:
# CLEAN THE DATASET D3

In [41]:
# Remove Duplicates
d3.drop_duplicates(inplace=True)

# Remove Post word:
d3["post"] = d3["post"].str.replace(r"(?i)^post:\s*", "", regex=True)

# Remove Question word:
d3["question"] = d3["question"].str.replace(r"(?i)Question:\s*", "", regex=True)

# Extract Yes/No
d3["stress_label"] = d3["response"].str.extract(r"(?i)^(yes|no)")

# Extract Reasoning Part
d3["stress_label"] = d3["response"].str.extract(r"(?i)^(yes|no)")


# Extract Reasoning Part
d3["reasoning"] = d3["response"].str.split("Reasoning:", expand=True)[1]
# Clean reasoning column
d3["reasoning"] = d3["reasoning"].str.strip()


# Lowercase Everything
d3["post"] = d3["post"].str.lower()
d3["question"] = d3["question"].str.lower()
d3["reasoning"] = d3["reasoning"].str.lower()
d3["stress_label"] = d3["stress_label"].str.lower()


# Remove NaN values 
d3 = d3.dropna()

# Drop Old Response Column
d3.drop(columns=["response"], inplace=True)


d3.head(3)

,post,question,stress_label,reasoning
0,all my life i've been going through shit (only...,"the answer to the ""does the post shows risk o...",yes,1. the individual mentions going through diffi...
3,give me one good reason i should not kill myse...,"the answer to the ""does the post shows risk o...",no,1. the post explicitly mentions thoughts of su...
5,i saw this tumblr post going around the intern...,"the answer to the ""does the post shows risk o...",yes,"1. the post mentions feeling depressed, being ..."

In [42]:
# Label Encode Yes/No

d3["stress_label"] = d3["stress_label"].map({"yes": 1, "no": 0})
d3["stress_label"].value_counts()

d3.head(3)

,post,question,stress_label,reasoning
0,all my life i've been going through shit (only...,"the answer to the ""does the post shows risk o...",1,1. the individual mentions going through diffi...
3,give me one good reason i should not kill myse...,"the answer to the ""does the post shows risk o...",0,1. the post explicitly mentions thoughts of su...
5,i saw this tumblr post going around the intern...,"the answer to the ""does the post shows risk o...",1,"1. the post mentions feeling depressed, being ..."

In [43]:
# Safe back the file into the d3

d3.to_csv("copy/d3.csv", index=False)

In [1]:
# MERGE ALL DATASETS

In [2]:
import pandas as pd

# Load cleaned datasets
d1 = pd.read_csv("copy/d1.csv")
d2 = pd.read_csv("copy/d2.csv")
d3 = pd.read_csv("copy/d3.csv")

# Merge them
final_merged_dataset = pd.concat([d1, d2, d3], ignore_index=True)

# Optional: remove duplicates again (safe practice)
final_merged_dataset.drop_duplicates(inplace=True)

# Save to your specified path
final_merged_dataset.to_csv(
    r"C:\Users\NIDHI\Desktop\NMIMS\SEM 6\ML\project\Mental-Health-Risk-Detection-ML\final_merged_dataset.csv",
    index=False
)

print("Datasets merged successfully ✅")

Datasets merged successfully ✅